#!/usr/bin/env bash
#script that displays the content of the /etc/passwd file, showing the username, user ID, and home directory path
file="/etc/passwd"

while IFS=':' read -r username x uid gid gecos home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo
done < "$file"
