#!/usr/bin/env bash
#script that displays a story based on the content of the /etc/passwd
file="/etc/passwd"

while IFS=':' read -r username _ uid gid _ home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode, more info about the user here: "
    echo
done < "$file"
