#!/usr/bin/env bash
#script that displays a story based on the content of the /etc/passwd
file="/etc/passwd"

while IFS=':' read -r username _ uid gid _ home shell; do
    read -r -a user_info < <(grep -w "$username" /etc/passwd)
    info=${user_info[4]}

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode, more info about the user here: $info"
    echo
done < "$file"
