#!/usr/bin/env bash
# Display the time from 0 to 12 hours and 1 to 59 minutes
hours=0
minutes=1

while ((hours <= 12)); do
    echo "Hour: $hours"
    while ((minutes <= 59)); do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
    minutes=1
done
