#!/usr/bin/env bash
# Display the content of the current directory in a list format,
# showing only the part of the name after the first dash
# Excludes hidden files

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        basename=$(echo "$file" | cut -d "-" -f 2-)
        echo "$basename"
    fi
done
