#!/usr/bin/env bash
#Bash script that gives you information about the school file.
filename="school"

if [[ -e "$filename" ]]; then
    if [[ -f "$filename" ]]; then
        echo "School is a regular file"
    fi
    if [[ -s "$filename" ]]; then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi
    echo "School file exists"
else
    echo "School file does not exist"
fi
