#!/usr/bin/env bash
#Bash script that gives you information about the school file.
filename="school"

if [[ -e "$filename" ]]; then
    if [[ -f "$filename" ]]; then
        echo "school is a regular file"
    fi
    if [[ -s "$filename" ]]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    echo "school file exists"
else
    echo "school file does not exist"
fi
