#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal
pid_file="/var/run/myscript.pid"
# Function to handle SIGTERM and SIGQUIT signals
cleanup() {
    echo "Deleting $pid_file"
    rm "$pid_file"
    exit 0
}
# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
}
# Register signal handlers
trap cleanup SIGQUIT SIGTERM
trap handle_sigint SIGINT
trap handle_sigterm SIGTERM
# Create pid file
echo $$ > "$pid_file"
# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 1
done
