#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          manage_my_process
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages the manage_my_process script
### END INIT INFO
# Change the path to your manage_my_process script
manage_my_process_script="/var/run/my_process.pid"
case "$1" in
    start)
        echo "manage_my_process started"
        /bin/bash "$manage_my_process_script" start
        ;;
    stop)
        echo "manage_my_process stopped"
        /bin/bash "$manage_my_process_script" stop
        ;;
    restart)
        echo "manage_my_process restarted"
        /bin/bash "$manage_my_process_script" restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
esac
exit 0
