#!/usr/bin/env bash
#!/bin/bash
### BEGIN INIT INFO
# Provides:          manage_my_process
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages the manage_my_process script
### END INIT INFO
# Change the path to your manage_my_process script
manage_my_process_script="https://github.com/Samenergy/alu-shell/tree/e4f6790ba10180989a6cf1ca15dafba83d9f8e5f/processes_and_signals"
pid_file="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f "$pid_file" ]; then
            echo "manage_my_process is already started"
            exit 1
        fi
        /bin/bash "$manage_my_process_script" > /dev/null 2>&1 &
        echo $! > "$pid_file"
        echo "manage_my_process started"
        ;;
    stop)
        if [ ! -f "$pid_file" ]; then
            echo "manage_my_process is not running"
            exit 1
        fi
        kill "$(cat "$pid_file")"
        rm "$pid_file"
        echo "manage_my_process stopped"
        ;;
    restart)
        if [ -f "$pid_file" ]; then
            kill "$(cat "$pid_file")"
            rm "$pid_file"
        fi
        /bin/bash "$manage_my_process_script" > /dev/null 2>&1 &
        echo $! > "$pid_file"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
