#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          manage_my_process
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages the manage_my_process script
### END INIT INFO

# Change the path to your manage_my_process script
manage_my_process_script="/path/to/manage_my_process.sh"

case "$1" in
    start)
        echo "Starting manage_my_process..."
        /bin/bash "$manage_my_process_script" start
        ;;
    stop)
        echo "Stopping manage_my_process..."
        /bin/bash "$manage_my_process_script" stop
        ;;
    restart)
        echo "Restarting manage_my_process..."
        /bin/bash "$manage_my_process_script" restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
